# Generated by Django 5.2.4 on 2025-07-30 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("ETF", "ETF"),
                            ("FOREX", "Forex"),
                            ("CRYPTO", "Crypto"),
                            ("FUTURE", "Future"),
                            ("INDEX", "Index"),
                            ("OTHER", "Other"),
                        ],
                        default="STOCK",
                        max_length=10,
                    ),
                ),
                ("exchange", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(blank=True, max_length=10)),
                (
                    "tick_size",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("lot_size", models.IntegerField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="OHLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("5m", "5 minutes"),
                            ("15m", "15 minutes"),
                            ("1h", "1 hour"),
                            ("1d", "1 day"),
                            ("1wk", "1 week"),
                            ("1mo", "1 month"),
                        ],
                        default="1d",
                        max_length=4,
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        help_text="Bar timestamp. Use period end in UTC."
                    ),
                ),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "adj_close",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=30)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlc",
                        to="marketdata.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "timeframe", "ts"],
                "indexes": [
                    models.Index(
                        fields=["asset", "timeframe", "ts"],
                        name="marketdata__asset_i_da56db_idx",
                    ),
                    models.Index(
                        fields=["timeframe", "ts"],
                        name="marketdata__timefra_a4690f_idx",
                    ),
                ],
                "unique_together": {("asset", "timeframe", "ts")},
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=30)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="marketdata.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["asset", "ts"], name="marketdata__asset_i_5b303d_idx"
                    )
                ],
            },
        ),
    ]
