# Generated by Django 5.2.4 on 2025-07-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="timezone",
            new_name="tz",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="lot_size",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="tick_size",
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("STOCK", "Stock"),
                    ("ETF", "ETF"),
                    ("FOREX", "Forex"),
                    ("CRYPTO", "Crypto"),
                    ("INDEX", "Index"),
                    ("FUTURE", "Future"),
                    ("OTHER", "Other"),
                ],
                default="STOCK",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PriceOHLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("5m", "5 minutes"),
                            ("15m", "15 minutes"),
                            ("1h", "1 hour"),
                            ("1d", "1 day"),
                            ("1wk", "1 week"),
                            ("1mo", "1 month"),
                        ],
                        default="1d",
                        max_length=4,
                    ),
                ),
                ("ts", models.DateTimeField(help_text="UTC bar end")),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "adj_close",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=30)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlc",
                        to="marketdata.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "timeframe", "ts"],
            },
        ),
        migrations.DeleteModel(
            name="OHLC",
        ),
        migrations.AddIndex(
            model_name="priceohlc",
            index=models.Index(
                fields=["asset", "timeframe", "ts"],
                name="marketdata__asset_i_381a61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="priceohlc",
            index=models.Index(
                fields=["timeframe", "ts"], name="marketdata__timefra_54c2c9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="priceohlc",
            unique_together={("asset", "timeframe", "ts")},
        ),
    ]
