# Generated by Django 5.2.4 on 2025-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0002_rename_timezone_asset_tz_remove_asset_lot_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
