# Generated by Django 5.2.4 on 2025-07-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("bio", models.TextField(blank=True)),
                ("preferred_assets", models.CharField(blank=True, max_length=200)),
                (
                    "daily_risk_limit_pct",
                    models.DecimalField(decimal_places=2, default=2, max_digits=5),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_sound", models.BooleanField(default=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
