# Generated by Django 5.2.4 on 2025-07-29 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8, help_text="Lots or units", max_digits=20
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("open_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=6,
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("tag", models.CharField(blank=True, max_length=50)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-open_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "symbol"], name="trading_tra_user_id_d6e973_idx"
                    ),
                    models.Index(
                        fields=["status"], name="trading_tra_status_252e0c_idx"
                    ),
                    models.Index(
                        fields=["open_time"], name="trading_tra_open_ti_9003f3_idx"
                    ),
                ],
            },
        ),
    ]
