from __future__ import annotations

from enum import Enum


class ProviderFailureCode(str, Enum):
    PROVIDER_NOT_CONFIGURED = "PROVIDER_NOT_CONFIGURED"
    PROVIDER_AUTH_FAILED = "PROVIDER_AUTH_FAILED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RESPONSE_INVALID = "PROVIDER_RESPONSE_INVALID"
    PROVIDER_ERROR = "PROVIDER_ERROR"


class StopCategory(str, Enum):
    COMPLETE = "COMPLETE"
    MAX_TOKENS = "MAX_TOKENS"
    OTHER = "OTHER"


FROZEN_PROVIDER_FAILURE_CODES = (
    "PROVIDER_NOT_CONFIGURED",
    "PROVIDER_AUTH_FAILED",
    "PROVIDER_RATE_LIMITED",
    "PROVIDER_TIMEOUT",
    "PROVIDER_RESPONSE_INVALID",
    "PROVIDER_ERROR",
)

FROZEN_STOP_CATEGORIES = (
    "COMPLETE",
    "MAX_TOKENS",
    "OTHER",
)
