from __future__ import annotations

from enum import Enum

from ..rag.schema import CROSS_SYMBOL_WARNING


class RejectionCode(str, Enum):
    REQUEST_STATE_NOT_OK = "REQUEST_STATE_NOT_OK"
    REQUEST_EMPTY_EVIDENCE = "REQUEST_EMPTY_EVIDENCE"
    REQUEST_MISMATCH = "REQUEST_MISMATCH"
    EVIDENCE_FIELD_INVALID = "EVIDENCE_FIELD_INVALID"
    SCHEMA_INVALID_JSON = "SCHEMA_INVALID_JSON"
    SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    SCHEMA_UNKNOWN_FIELD = "SCHEMA_UNKNOWN_FIELD"
    SCHEMA_MISSING_FIELD = "SCHEMA_MISSING_FIELD"
    SCHEMA_TYPE_ERROR = "SCHEMA_TYPE_ERROR"
    SCHEMA_LIMIT_EXCEEDED = "SCHEMA_LIMIT_EXCEEDED"
    ANSWER_EMPTY = "ANSWER_EMPTY"
    CITATION_MISSING = "CITATION_MISSING"
    CITATION_UNKNOWN_ALIAS = "CITATION_UNKNOWN_ALIAS"
    CITATION_DUPLICATE = "CITATION_DUPLICATE"
    CITATION_INLINE_MISMATCH = "CITATION_INLINE_MISMATCH"
    CITATION_INTERNAL_ID = "CITATION_INTERNAL_ID"
    CLAIM_ALIAS_NOT_CITED = "CLAIM_ALIAS_NOT_CITED"
    CLAIM_FIELD_NOT_CLAIMABLE = "CLAIM_FIELD_NOT_CLAIMABLE"
    CLAIM_VALUE_MISMATCH = "CLAIM_VALUE_MISMATCH"
    CLAIM_FIELD_UNAVAILABLE = "CLAIM_FIELD_UNAVAILABLE"
    NUMBER_UNGROUNDED = "NUMBER_UNGROUNDED"
    IDENTIFIER_UNGROUNDED = "IDENTIFIER_UNGROUNDED"
    STATUS_CONTRADICTION = "STATUS_CONTRADICTION"
    LIMITATION_REQUIRED_MISSING = "LIMITATION_REQUIRED_MISSING"
    LIMITATION_UNKNOWN_CODE = "LIMITATION_UNKNOWN_CODE"
    PROHIBITED_RECOMMENDATION = "PROHIBITED_RECOMMENDATION"
    PROHIBITED_PREDICTION = "PROHIBITED_PREDICTION"
    PROHIBITED_PRECISION_CLAIM = "PROHIBITED_PRECISION_CLAIM"
    PROHIBITED_COUNTERFACTUAL = "PROHIBITED_COUNTERFACTUAL"
    LEAKAGE_DETECTED = "LEAKAGE_DETECTED"


class LimitationCode(str, Enum):
    APPROXIMATE_M1_EVIDENCE = "APPROXIMATE_M1_EVIDENCE"
    EVIDENCE_UNAVAILABLE = "EVIDENCE_UNAVAILABLE"
    CROSS_SYMBOL_NOT_COMPARABLE = "CROSS_SYMBOL_NOT_COMPARABLE"
    PARTIAL_EVIDENCE = "PARTIAL_EVIDENCE"


class FieldType(str, Enum):
    IDENTIFIER = "IDENTIFIER"
    ENUM = "ENUM"
    DECIMAL = "DECIMAL"
    INTEGER = "INTEGER"
    TIMESTAMP = "TIMESTAMP"
    TEXT = "TEXT"


class ValidationStatus(str, Enum):
    PASSED_DETERMINISTIC_CHECKS = "PASSED_DETERMINISTIC_CHECKS"
    REJECTED = "REJECTED"


FROZEN_REJECTION_CODES = (
    "REQUEST_STATE_NOT_OK",
    "REQUEST_EMPTY_EVIDENCE",
    "REQUEST_MISMATCH",
    "EVIDENCE_FIELD_INVALID",
    "SCHEMA_INVALID_JSON",
    "SCHEMA_VERSION_MISMATCH",
    "SCHEMA_UNKNOWN_FIELD",
    "SCHEMA_MISSING_FIELD",
    "SCHEMA_TYPE_ERROR",
    "SCHEMA_LIMIT_EXCEEDED",
    "ANSWER_EMPTY",
    "CITATION_MISSING",
    "CITATION_UNKNOWN_ALIAS",
    "CITATION_DUPLICATE",
    "CITATION_INLINE_MISMATCH",
    "CITATION_INTERNAL_ID",
    "CLAIM_ALIAS_NOT_CITED",
    "CLAIM_FIELD_NOT_CLAIMABLE",
    "CLAIM_VALUE_MISMATCH",
    "CLAIM_FIELD_UNAVAILABLE",
    "NUMBER_UNGROUNDED",
    "IDENTIFIER_UNGROUNDED",
    "STATUS_CONTRADICTION",
    "LIMITATION_REQUIRED_MISSING",
    "LIMITATION_UNKNOWN_CODE",
    "PROHIBITED_RECOMMENDATION",
    "PROHIBITED_PREDICTION",
    "PROHIBITED_PRECISION_CLAIM",
    "PROHIBITED_COUNTERFACTUAL",
    "LEAKAGE_DETECTED",
)

FROZEN_LIMITATION_CODES = (
    "APPROXIMATE_M1_EVIDENCE",
    "EVIDENCE_UNAVAILABLE",
    "CROSS_SYMBOL_NOT_COMPARABLE",
    "PARTIAL_EVIDENCE",
)

LIMITATION_WORDING = {
    LimitationCode.APPROXIMATE_M1_EVIDENCE: (
        "M1 bar evidence is approximate window evidence, not exact extrema."
    ),
    LimitationCode.EVIDENCE_UNAVAILABLE: (
        "Some requested bar evidence is unavailable."
    ),
    LimitationCode.CROSS_SYMBOL_NOT_COMPARABLE: CROSS_SYMBOL_WARNING,
    LimitationCode.PARTIAL_EVIDENCE: (
        "Only a subset of matching evidence was returned."
    ),
}


class GroundingError(Exception):
    def __init__(self, code: RejectionCode, message: str = "") -> None:
        self.code = code
        super().__init__(message or code.value)


__all__ = [
    "FROZEN_LIMITATION_CODES",
    "FROZEN_REJECTION_CODES",
    "LIMITATION_WORDING",
    "FieldType",
    "GroundingError",
    "LimitationCode",
    "RejectionCode",
    "ValidationStatus",
]
